import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Avatar from '../components/Avatar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="form-widget">
        <Avatar
          url={"https://gravatar.com/avatar/7cbc982dc26dc5690e0dd5e61c29ef81?s=400&d=robohash&r=x"}
          size={150}
          onUpload={(url) => {
            setAvatarUrl(url)
            updateProfile({ username, website, avatar_url: url })
          }}
        />
      </div>


    </div>
  )
}
